title: How to use HashiCorp Vault for Cockroach Database authentication
description: Issuing and rotating digital certificates can be a painful process. Cockroach Database uses digital certififates for authentiation. This blog post demonstrates (with a docker-compose example) how to automate the process of issuing and renewing short-lived certificates with HashiCorp Vault.
github_username:  rinokadijk
base_url: /vault-cockroach/
url: "https://rinokadijk.github.io"
plugins:
- jekyll-sitemap

markdown: kramdown
kramdown:
  input: GFM

excerpt_separator: <!--description-->
